### PR TITLE
Add ability to pass addonName and fix paths

### LINKED ISSUE #36: Addon Support: Properly name files in `lcov.info`
Currently `lcov.info` namespaces addon code as: `SF:modules/addon-name/models/ab.js`

It should be: `SF:addon/models/ab.js` so that code coverage tools like Coveralls can properly parse the file.

I solved this using `sed s/SF:modules\\/addon-name/SF:addon/` in my build jobs, but we probably should work on properly renaming it and save everyone the trouble. If someone could point me to some lines or functions to look at for context, I'll take it on.

### PR DESCRIPTION
**Pull request by rwwagner90**
This allows passing `addonName` in the config and it will replace `modules/my-addon` with `addon` in the lcov.info file. This should allow proper file mapping for things like Code Climate and Coveralls. Does this approach look okay to you @rwjblue and @kategengler?

Resolves #36

### CODE REVIEW

**Comment by rwwagner90** [comment]
We could probably also use this same method to remove the `tests/` output, since we don't want coverage for tests right?

**Comment by offirgolan** [comment]
@rwwagner90 is there no way to get the default addon name from the addon's package.json?

File: lib/config.js [hunk 1]
```diff
@@ -36,6 +36,7 @@ function config(root) {
  */
 function getDefaultConfig() {
   return {
+    addonName: null,
```
Comment (offirgolan) [inline lib/config.js]: You can pass the root from the parent `config` method and do something like this:

`addonName: path.join(root, 'package.json').name`

File: lib/attach-middleware.js [hunk 2]
```diff
@@ -20,6 +20,16 @@ module.exports = function(app, options) {
       var reporter = new Istanbul.Reporter(null, path.join(options.root, _config.coverageFolder));
       var sync = false;
 
+      // If we define an addonName, strip modules/addonName and replace with 'addon'
+      if (_config.addonName) {
+        Object.keys(req.body).forEach(function(key) {
+          if (key.includes('modules/' + _config.addonName)) {
+            req.body[key].path = req.body[key].path
+              .replace(new RegExp('modules/' + _config.addonName, 'g'), 'addon');
```
Comment (offirgolan) [inline lib/attach-middleware.js]: I dont think you need to create a new `RegExp` every time.

**Comment by rwwagner90** [comment]
@offirgolan we can definitely pull from package.json, I was just going with the simplest first implementation. How would you recommend differentiating between addons and apps in that case? They would both have a `name` in package.json.

**Comment by rwwagner90** [comment]
@offirgolan I updated with your suggestions, please take a look 😄

**Comment by offirgolan** [comment]
@rwwagner90 lgtm 😄! Thanks for taking initiative on this.

**Comment by rwwagner90** [comment]
No problem @offirgolan! I definitely want to help this addon succeed 😄

**Comment by rwwagner90** [comment]
@rwjblue and @kategengler PTAL when you get a chance. It's fairly small and straight forward. Will gladly make any changes you may want to get it merged in.

**Comment by arjansingh** [comment]
LGTM

**Comment by rwjblue** [comment]
Thanks @rwwagner90!

**Comment by rwjblue** [comment]
Published in 0.3.5
