### PR TITLE
[Fixes #111] Update dependencies, get babel instrumenter working

### LINKED ISSUE #111: Plugin fails with ember-cli 2.13 and useBabelInstrumenter: true
I assume this is known, but for tracking purposes:

```
$ ember -v
ember-cli: 2.13.0-beta.4
node: 6.10.1
os: darwin x64
$ ember new coverage-test
$ cd coverage-test
$ ember install ember-cli-code-coverage
$ COVERAGE=true ember test
...
1..8
# tests 8
# pass  8
# skip  0
# fail  0

# ok
$ echo "module.exports = { useBabelInstrumenter: true };" > config/coverage.js
$ COVERAGE=true ember test
 TypeError: The plugin [null,{}] didn't export a Plugin instance
    at PluginManager.validate (coverage-test/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (coverage-test/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (coverage-test/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (coverage-test/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (coverage-test/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Instrumenter.instrumentSync (coverage-test/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:36:45)
    at CoverageInstrumenter.processString (coverage-test/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:113:25)
    at CoverageInstrumenter.processFile (coverage-test/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (coverage-test/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (coverage-test/node_modules/rsvp/dist/rsvp.js:539:12)
Unable to cover: app/resolver.js . Try setting useBabelInstrumenter to true. 
 TypeError: The plugin [null,{}] didn't export a Plugin instance
    at PluginManager.validate (coverage-test/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (coverage-test/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (coverage-test/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (coverage-test/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (coverage-test/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Instrumenter.instrumentSync (coverage-test/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:36:45)
    at CoverageInstrumenter.processString (coverage-test/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:113:25)
    at CoverageInstrumenter.processFile (coverage-test/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (coverage-test/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (coverage-test/node_modules/rsvp/dist/rsvp.js:539:12)
...
```

I'm pretty green with Babel and Babel plugins, but if pointed in the right direction I can take a look at making this work!

### PR DESCRIPTION
**Pull request by paulcwatts**
This updates to the latest ember-cli and the latest blueprint. It also adds a yarn.lock file.

I also added an integration test for using the babel instrumenter and fixed it so the test passes. I've also been using ember-try to test against older LTS versions, and it seems to work.

Another addition might be to add ember-try support to travis.yml, and to update the other non-ember/non-babel dependencies.

Comments welcome, or suggestions for testing.

Still to do:
- [X] Get ES2017 async functions working

### CODE REVIEW

**Comment by paulcwatts** [comment]
Issue #1: Neither ember-cli 2.13 nor yarn support Node 0.12. Is there a reason to keep supporting Node 0.12 for this project?

**Comment by kellyselden** [comment]
@paulcwatts Nope, Node 0.12 can be dropped.

**Comment by kellyselden** [comment]
Is it possible to break this up? It's a little hard to review only the babel changes for me with all the ember-cli update noise.

**Comment by paulcwatts** [comment]
@kellyselden I can try that.

**Comment by paulcwatts** [comment]
The trouble is that for apps written against ember-cli < 2.13, we cannot use the app's babel options, _including this addon's dummy app_.

This reveals another issue where simply upgrading this blueprint to 2.13 won't work for apps that are still on older versions ember-cli. We'd need to test against older versions of ember-cli, which is made easier by using ember-try or potentially https://github.com/tomdale/ember-cli-addon-tests. 

So splitting up this PR is possible, but if the ember-cli upgrade doesn't come first, the babel fix becomes more difficult and involves throw away work.

**Comment by kellyselden** [comment]
@paulcwatts alright lets keep it together then.

**Comment by paulcwatts** [comment]
Issue 2: async functions don't seem to be working.

**Comment by rondale-sc** [comment]
@paulcwatts Has there been any movement on this since last update?  I can attest that as of the last  commit in this PR coverage fails for my codebase.  I suspect it is async functions as you posited.

**Comment by paulcwatts** [comment]
@rondale-sc I haven't had time to work on it since then, I may have time later this week or this weekend. Definitely next week.

**Comment by paulcwatts** [comment]
The trouble is that the Babel instrumenter uses esprima for its parser, but esprima doesn't yet support async functions:

```
> code
'import Ember from \'ember\';\nexport default Ember.Route.extend({\n  async model() {\n    return {};\n  }\n});'
> let prog = esprima.parse(code, {loc: true, range: true, comment: true, sourceType: 'module'});
Error: Line 3: Unexpected identifier
    at ErrorHandler.constructError (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:3414:27)
    at Parser.unexpectedTokenError (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:542:39)
    at Parser.throwUnexpectedToken (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:552:21)
    at Parser.expect (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:716:19)
    at Parser.expectCommaSeparator (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:735:19)
    at Parser.parseObjectInitializer (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:1135:23)
    at Parser.inheritCoverGrammar (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parsePrimaryExpression (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:905:38)
    at Parser.inheritCoverGrammar (ember-cli-code-coverage/node_modules/esprima/dist/esprima.js:833:37)
```

https://github.com/jquery/esprima/pull/1597
https://github.com/jquery/esprima/issues/1638

I can look into switching to using Babylon as the parser, but I don't know yet what that will involve.

**Comment by paulcwatts** [comment]
I am able to get them to work by manually adding the async-to-generator plugin to the list of babelOptions when it is invoked by the babel instrumenter here: 

```javascript
  var plugins = this.babelOptions.plugins;
  plugins.push(require('babel-plugin-transform-async-to-generator'));
  var result = this._r = (0, babelTransform)(code, extend({}, this.babelOptions, { filename: fileName }));
```

This is ugly, but I don't know why the babel options don't already include a plugin to parse async functions.

**Comment by rondale-sc** [comment]
@paulcwatts Have you attempted to upgrade istanbul to alpha?

I think maybe this was resolved in their alpha branch: https://github.com/gotwarlost/istanbul/issues/733

Though I could be barking up the wrong tree.

**Comment by rondale-sc** [comment]
Does your fix belong in the host application or in this addon?

The additional transform linked above I mean.

*(also, as a side note I believe I spoke too soon on the istanbul alpha upgrade.  Seems like that'd only work with node 7+)*

**Comment by rtorr** [comment]
Any updates with this? :D

**Comment by paulcwatts** [comment]
With the latest push, async functions seem to be working -- at least on one of my projects. I'd appreciate some other folks check to see if this branch works for them!

The build failure seems to be a random timeout error: I can't seem to restart the build to see if a rebuild fixes it.

**Comment by dfreeman** [comment]
@paulcwatts Your fix seems to work for async functions, but it doesn't account for other transforms people might be using (decorators, for instance) — maybe users need to be able to just specify a set of Babel plugins in `config/coverage.js`?

**Comment by paulcwatts** [comment]
@dfreeman Good point. I can add a configuration option. Hopefully it will be temporary, as I'd like to investigate switching to babel-plugin-istanbul. If babel-plugin-instanbul can be used then we can potentially deprecate the new option along with the useBabelInstrumenter option.

**Comment by paulcwatts** [comment]
@dfreeman Can you test the latest to see if it works for you? You should just be able to add a `babelPlugins` list to coverage.js (see the updated README).

**Comment by dfreeman** [comment]
@paulcwatts It _almost_ works. I tested with `babel-plugin-transform-decorators-legacy` and ran into an issue where it hangs off a `default` key instead of being the entire module (i.e. [this line](https://github.com/paulcwatts/ember-cli-code-coverage/blob/update-babel/lib/babel-istanbul-instrumenter.js#L40) would have needed to be `require(plugin).default` instead.)

It looks like Babel happily accepts just strings for its list of plugins, and then internally handles the `default` disparity for you — it also takes care of prepending `babel-plugin-` if you leave it out. Given that, might make sense to drop the `require` call completely and just pass through the specified plugins untouched?

**Comment by paulcwatts** [comment]
@dfreeman I made that change (again, the build failed for intermittent timeout reasons). I temporarily added decorators plugin and ran the tests and it seemed to work.

**Comment by dfreeman** [comment]
🎉  Looks good to me locally. Thanks @paulcwatts!

**Comment by paulcwatts** [comment]
@kategengler @rwjblue @kellyselden I believe all the issues have been resolved (you can restart the Travis build to make sure). Is there anything else before this can be accepted?

File: .gitignore [hunk 1]
```diff
@@ -12,6 +12,8 @@
 /.sass-cache
 /connect.lock
 /coverage/*
+/coverage_*
 /libpeerconnection.log
-npm-debug.log
+npm-debug.log*
 testem.log
+/.idea
```
Comment (kellyselden) [inline .gitignore]: Can you please remove IDE specific ignores.

File: lib/babel-istanbul-instrumenter.js [hunk 2]
```diff
@@ -33,6 +32,13 @@ Instrumenter.prototype = Object.create(istanbul.Instrumenter.prototype);
 Instrumenter.prototype.constructor = Instrumenter;
 
 Instrumenter.prototype.instrumentSync = function(code, fileName) {
+  var plugins = this.babelOptions.plugins;
+  // If we're running in coverage, we're assuming that this is running in CI or in some
+  // form of test scenario and not being built for production. So it's fine to always
+  // force this plugin to work.
+  for (var plugin of this.plugins) {
```
Comment (kellyselden) [inline lib/babel-istanbul-instrumenter.js]: Do you need to protect against prototype members here? (hasOwnProperty)

File: lib/coverage-instrumenter.js [hunk 3]
```diff
@@ -1,8 +1,5 @@
-'use strict';
-
 require('string.prototype.startswith');
 var existsSync = require('exists-sync');
-var extend = require('extend');
```
Comment (kellyselden) [inline lib/coverage-instrumenter.js]: Can this now be removed from package.json?

File: tests/dummy/app/templates/application.hbs [hunk 4]
```diff
@@ -1,3 +1,5 @@
-<h2 id="title">Welcome to Ember</h2>
+{{!-- The following component displays Ember's default welcome message. --}}
+{{welcome-page}}
```
Comment (kellyselden) [inline tests/dummy/app/templates/application.hbs]: I believe this component is invalid because we don't have the ember-welcome-page addon.

File: lib/babel-istanbul-instrumenter.js (hunk 2 above)
Comment (paulcwatts) [inline lib/babel-istanbul-instrumenter.js]: This is normally going to be a simple array, but I can do it just to be absolutely safe.

File: lib/coverage-instrumenter.js (hunk 3 above)
Comment (paulcwatts) [inline lib/coverage-instrumenter.js]: It's still used in babel-istanbul-instrumenter.js.

**Comment by paulcwatts** [comment]
@kellyselden My reasoning behind the plugin default was to match the language version Ember CLI supports by default. I could be wrong, but Ember CLI 2.13 seems to support ES2017 by default (given the value in eslintrc). In order for an app to support decorators, you have to add additional plugins to the host app.

**Comment by kellyselden** [comment]
@paulcwatts OK. I wasn't aware of that reasoning. The plugin default looks good to me.

**Comment by paulcwatts** [comment]
I'll add a comment in the config to that effect.

File: .gitignore (hunk 1 above)
Comment (kellyselden) [inline .gitignore]: (it's a convention of ember projects not to include IDE specific code)

**Comment by kellyselden** [comment]
> I'll add a comment in the config to that effect.

Even better!

File: lib/babel-istanbul-instrumenter.js (hunk 2 above)
Comment (paulcwatts) [inline lib/babel-istanbul-instrumenter.js]: I think we are safe here, because this is using "for...of" rather than "for...in". "for...of" only iterates over the elements of the collection:

```javascript
Object.prototype.objCustom = function() {}; 
Array.prototype.arrCustom = function() {};

let iterable = [3, 5, 7];
iterable.foo = 'hello';

for (let i in iterable) {
  console.log(i); // logs 0, 1, 2, "foo", "arrCustom", "objCustom"
}

for (let i of iterable) {
  console.log(i); // logs 3, 5, 7
}
```

Comment (kellyselden) [inline lib/babel-istanbul-instrumenter.js]: I missed that, Looks good.

**Comment by paulcwatts** [comment]
@kellyselden Review changes made.

**Comment by paulcwatts** [comment]
@rwjblue @kategengler This has been reviewed and approved by @kellyselden, what else needs to happen to get this merged?

File: config/ember-try.js [hunk 5]
```diff
@@ -0,0 +1,91 @@
+/* eslint-env node */
```
Comment (kellyselden) [inline config/ember-try.js]: This file should be removed, as ember-try isn't used in this repo

File: test/helpers/run-command.js [hunk 6]
```diff
@@ -1,5 +1,3 @@
-'use strict';
```
Comment (kellyselden) [inline test/helpers/run-command.js]: why all the use strict removals?

File: tests/dummy/config/coverage-babel.js [hunk 7]
```diff
@@ -0,0 +1,5 @@
+/*jshint node:true*/
```
Comment (kellyselden) [inline tests/dummy/config/coverage-babel.js]: jshint => eslint

File: tests/test-helper.js [hunk 8]
```diff
@@ -2,5 +2,7 @@ import resolver from './helpers/resolver';
 import {
   setResolver
 } from 'ember-qunit';
+// import { start } from 'ember-cli-qunit';
```
Comment (kellyselden) [inline tests/test-helper.js]: was this causing problems?

File: config/ember-try.js (hunk 5 above)
Comment (paulcwatts) [inline config/ember-try.js]: At some point I was thinking that it would be nice to switch to using ember-try for the tests, but until then I'll remove it.

File: test/helpers/run-command.js (hunk 6 above)
Comment (paulcwatts) [inline test/helpers/run-command.js]: When I first updated the blueprint, there were a bunch of eslint errors around using "use strict" with `sourceType: module`. But for some reason I'm not getting those anymore, so I'll put them back.

File: tests/test-helper.js (hunk 8 above)
Comment (paulcwatts) [inline tests/test-helper.js]: If I recall, the tests didn't work with ember-cli-qunit@4.0.0-beta1. They apparently work with 4.0.0 now.

**Comment by paulcwatts** [comment]
@kellyselden OK all of the changes were made (the build failed intermittently again). Are there any other changes that need to be made? What else needs to be done to get this to be merged? I'm sure a lot of folks would like this support, and it's blocking other PRs like https://github.com/kategengler/ember-cli-code-coverage/pull/119

File: .eslintrc.js [hunk 9]
```diff
@@ -19,9 +20,6 @@ module.exports = {
     // JSHint "proto", disabled due to warnings
     'no-proto': 0,
 
-    // JSHint "strict"
-    'strict': [2, 'global'],
```
Comment (kellyselden) [inline .eslintrc.js]: is this necessary to remove now that the `use strict` issue is resolved?

Comment (kellyselden) [inline .eslintrc.js]: is this necessary to remove now that the use strict issue is resolved?

Comment (paulcwatts) [inline .eslintrc.js]: So if I add that, then I get:

```
> ember-cli-code-coverage@0.3.12 lint /Users/paulw/Work/stuff/ember-cli-code-coverage
> eslint config lib test tests *.js


/Users/paulw/.../ember-cli-code-coverage/config/environment.js
  2:1  error  'use strict' is unnecessary inside of modules  strict

/Users/paulw/.../ember-cli-code-coverage/config/release.js
  1:1  error  'use strict' is unnecessary inside of modules  strict

/Users/paulw/.../ember-cli-code-coverage/lib/attach-middleware.js
  1:1  error  'use strict' is unnecessary inside of modules  strict

....
```

So which do you want, do you want the eslint rule or do you want the "use stricts"? Personally I'd rather have it hue closer to the default ember-cli blueprint, but that's just my opinion.

Comment (kellyselden) [inline .eslintrc.js]: I think the way you have it now is good

**Comment by kellyselden** [comment]
I'd like someone a little closer to the codebase do the merge, but if no one does it soon I'll merge.

cc @rwjblue @kategengler

**Comment by paulcwatts** [comment]
OK, what else needs to get done in order for this to be merged?

**Comment by paulcwatts** [comment]
Thanks @kellyselden

**Comment by kellyselden** [comment]
I forgot to bring this up in the ember-cli meeting today. I'm sorry 😢

**Comment by mattmarcum** [comment]
Is there anything I can do to help get this merged?  😄

**Comment by ming-codes** [comment]
Cutting release for this?

**Comment by ming-codes** [comment]
Ping @kellyselden @rwjblue release?

**Comment by kellyselden** [comment]
Released in v0.4.0.

**Comment by rtorr** [comment]
Yay!
