### PR TITLE
Filter out files from addons, fix file paths, and rename config file

### LINKED ISSUE #4: Change config file name?
`config/coverage-config.js` seems redundant, what do you think about changing the file to `config/coverage.js` or `config/code-coverage.js`?

### LINKED ISSUE #7: files from addons bleed into coverage results
Not all the files in the picture are mine, some come from addons:
capture2

### LINKED ISSUE #8: paths in "lcov.info" don't relate to project setup
After I resolve #7, I saw that the paths in "lcov.info" are not right. I was getting in my coveralls logs `Error: ENOENT: no such file or directory, open '/home/travis/build/kellyselden/package-hint-historic-resolver/package-hint-historic-resolver/adapters/application.js'`. It seems the second "app name" needs to be either "app" or "addon" for the path to be correct for coveralls and maybe other reporters.

### PR DESCRIPTION
**Pull request by sandersky**
* **Filter Out Files from Addons**
The code coverage currently being reported by this addon includes files from Ember addons the consuming app/addon depends on, which make the metrics a little bit misleading. This pull request filters out those files so the coverage reported is only for files from the consumers app/addon. Resolves #7.

* **Fix File Paths**
Currently the file paths being reported in coverage look something like `foo/components/bar.js` which is actually referencing the file at `app/components/bar.js`. Since the file paths being reported are not real file paths lcov viewers do not properly map the lcov info to the corresponding files, making it somewhat hard to utilize. This pull request fixes the file paths so that they reference real files, making editor plugins such as `lcov-info` for Atom highlight coverage in files. Resolves #8.

* **Rename Config File**
Renamed the configuration file from `config/coverage-config.js` to `config/coverage.js`. Resolves #4.

### CODE REVIEW

**Comment by sandersky** [comment]
@kategengler would love to get this reviewed/merged as soon as possible so my team can start switching over to `ember-cli-code-coverage` from `ember-cli-blanket`.

File: index.js [hunk 1]
```diff
@@ -19,15 +92,24 @@ module.exports = {
...
-      var instrumentedNode = new CoverageInstrumenter(appFiles, {annotation: 'Instrumenting for code coverage'});
-      return new BroccoliMergeTrees([tree, instrumentedNode], { overwrite: true });
+  preprocessTree: function(type, tree) {
+    if (!this._coverageIsEnabled() || type !== 'js') {
+      return tree;
     }
-    return tree;
+
+    var packageFilePath = path.join(this.project.root, 'package.json');
+    var appName = JSON.parse(fs.readFileSync(packageFilePath)).name;
```
Comment (kellyselden) [inline index.js]: You can probably get this via a property on `this`.

Comment (sandersky) [inline index.js]: Agreed, committed a change to use `this.parent.pkg.name` instead.

File: lib/babel-istanbul-instrumenter.js [hunk 2]
```diff
@@ -0,0 +1,349 @@
+/* global Symbol */
```
Comment (kellyselden) [inline lib/babel-istanbul-instrumenter.js]: Did you write this file, or is copied from somewhere?

Comment (sandersky) [inline lib/babel-istanbul-instrumenter.js]: I got it from a co-workers fork here: https://github.com/sophypal/ember-cli-code-coverage. @sophypal was this copied from *isparta*?

Comment (sandersky) [inline lib/babel-istanbul-instrumenter.js]: I added a comment as to where the code came from and did some minor cleanup on it.

Comment (sophypal) [inline lib/babel-istanbul-instrumenter.js]: This was from `isparta` which is not maintained anymore.  I actually meant to clean up my fork so it doesn't look like it came straight out of `babel`.

**Comment by kellyselden** [comment]
This PR is a behemoth, and I think the first step to getting it all merged is to break it into pieces. For all those issues linked, could you please create a separate PR?

**Comment by patcoll** [comment]
This PR is indeed large. However, it seems stable. I am adapting it in my app right now without problems.

**Comment by sglanzer** [comment]
@kellyselden I don't think it makes a lot of sense to make @sandersky break this into separate PRs to get this reviewed/merged unless there are perceived issues or controversy with portions of the PR.

He's done a ton of work to add a bunch of useful features to this addon, why not make it easier on him and review the current PR?

**Comment by rwjblue** [comment]
On the one hand it is pretty annoying to split up this PR, but on the other it is harder to review it and understand the various changes needed.  

I'm going to try and review this PR to provide actionable feedback either way...

File: index.js [hunk 3]
```diff
@@ -12,36 +12,176 @@ var config = require('./lib/config');
...
+
+  /**
+   * Check if a template file exists within the current app/addon
+   * Note: Template files are already compiled into JavaScript files so we must
+   * check for the pre-compiled .hbs file
+   * @param {String} relativePath - path to file within current app/addon
+   * @returns {Boolean} whether or not the file exists within the current app/addon
+   */
+  _doesTemplateFileExist: function(relativePath) {
+    relativePath = relativePath.replace('.js', '.hbs');
```
Comment (rwjblue) [inline index.js]: We should support any known template extension.  You can get these extensions via:

```js
    var templateExtensions = this.registry.extensionsForType('template');
```

(stolen from https://github.com/ember-cli/ember-cli/blob/d987b4f7dd1e8b2476193b47ac0e5e489cb7f585/lib/models/addon.js#L605)

File: index.js [hunk 4]
```diff
@@ -12,36 +12,176 @@ var config = require('./lib/config');
...
+  /**
+   * Check if a file exists within the current app/addon
+   * @param {String} relativePath - path to file within current app/addon
+   * @returns {Boolean} whether or not the file exists within the current app/addon
+   */
+  _doesFileExistInCurrentProject: function(relativePath) {
+    relativePath = path.join('app', relativePath);
+
+    try {
+      fs.statSync(relativePath);
```
Comment (rwjblue) [inline index.js]: I'd prefer to use `exists-sync` package to `try`/`catch`.

File: index.js [hunk 5]
```diff
@@ -12,36 +12,176 @@ var config = require('./lib/config');
...
+  /**
+   * Check if a file exists within the dummy app
+   * @param {String} relativePath - path to file within dummy app
+   * @returns {Boolean} whether or not the file exists within the dummy app
+   */
+  _doesFileExistInDummyApp: function(relativePath) {
+    relativePath = path.join('tests', 'dummy', 'app', relativePath);
+
+    try {
+      fs.statSync(relativePath);
```
Comment (rwjblue) [inline index.js]: I'd prefer to use `exists-sync` package to `try`/`catch`.

File: index.js [hunk 6]
```diff
@@ -12,36 +12,176 @@ var config = require('./lib/config');
...
+   * @returns {[type]} processed tree
+   */
+  preprocessTree: function(type, tree) {
+    // If coverage isn't enabled or tree is not JavaScript tree then we don't need to alter the tree
+    if (!this._isCoverageEnabled() || type !== 'js') {
+      return tree;
     }
-    return tree;
+
+    // Make sure we exlcude files defined in the configuration as well as files from addons
```
Comment (rwjblue) [inline index.js]: typo `exlcude` -> `exclude`

File: index.js [hunk 7]
```diff
@@ -12,36 +12,176 @@ var config = require('./lib/config');
...
+    excludes.push(this._filterOutAddonFiles.bind(this, name));
+    return excludes;
+  },
+
+  /**
+   * Determine whether or not coverage is enabled
+   * @returns {Boolean} whether or not coverage is enabled
+   */
+  _isCoverageEnabled: function() {
+    var value = process.env[this._getConfig().coverageEnvVar];
```
Comment (rwjblue) [inline index.js]: Why not go with `return !!process.env[this._getConfig().coverageEnvVar];`?  What does the extra complexity here gain us?  Is this just to support setting `COVERAGE=false`?  If that is it, maybe something like this would be simpler:

```js
var value  = process.env[this._getConfig().coverageEnvVar];

return value && value !== 'false';
```

Or (if `true` is the magic value):

```js
return process.env[this._getConfig().coverageEnvVar] + '' === 'true';
```

File: lib/babel-istanbul-instrumenter.js [hunk 8]
```diff
@@ -0,0 +1,256 @@
+/**
```
Comment (rwjblue) [inline lib/babel-istanbul-instrumenter.js]: If we are going to check this file into the repo in ES5, and isparta is unmaintained we should probably just rewrite this in idiomatic ES5 style instead of using the babel transpiled version of the isparta code.

Specifically, things like the following make life a little harder:

```js
var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(Instrumenter).call(this));
//...snip...
var result = this._r = (0, babelTransform)(code, extend({}, this.babelOptions, { filename: fileName }));
```

Comment (rwjblue) [inline lib/babel-istanbul-instrumenter.js]: This file is pretty complicated, and ultimately makes the maintenance of this repo much harder (at least it adds significantly to the cognitive overhead required to fix/change things).  Maybe we should start out with the other changes, and circle back around to this one if it is absolutely critical...

File: lib/coverage-instrumenter.js [hunk 9]
```diff
@@ -16,12 +56,18 @@ CoverageInstrumenter.prototype.extensions = ['js'];
 CoverageInstrumenter.prototype.targetExtension = 'js';
 
 CoverageInstrumenter.prototype.processString = function(content, relativePath) {
-  var instrumenter = new Istanbul.Instrumenter({
+  var instrumenter = new Instrumenter({
+    babel: {
+      blacklist: ['es6.modules'],
+      nonStandard: false,
+      optional: ['es7.decorators']
```
Comment (rwjblue) [inline lib/coverage-instrumenter.js]: This seems odd to hard code. Ultimately, we need to pass through whatever the app being compiled is using for its plugins...

File: lib/coverage-instrumenter.js [hunk 10]
```diff
@@ -1,12 +1,52 @@
 'use strict';
 
 var Filter = require('broccoli-filter');
-var Istanbul = require('istanbul');
+var Instrumenter = require('./babel-istanbul-instrumenter');
+var fs = require('fs');
+var path = require('path');
+
+function getPathForRealFile(relativePath, root) {
```
Comment (rwjblue) [inline lib/coverage-instrumenter.js]: This should share the logic from `index.js`, where we are doing a very similar thing.

File: lib/coverage-instrumenter.js [hunk 11]
```diff
@@ -1,12 +1,52 @@
...
+  try {
```
Comment (rwjblue) [inline lib/coverage-instrumenter.js]: we should be able to avoid `try`/`catch` here...

File: lib/coverage-instrumenter.js [hunk 12]
```diff
@@ -1,12 +1,52 @@
...
+    fs.statSync(path.join(root, relativePath))
+    return relativePath
+  } catch (err) {
```
Comment (rwjblue) [inline lib/coverage-instrumenter.js]: we should be able to avoid nested `try`/`catch` here...

File: lib/coverage-instrumenter.js [hunk 13]
```diff
@@ -1,12 +1,52 @@
...
+    try {
+      var templatePath = relativePath.replace('.js', '.hbs')
```
Comment (rwjblue) [inline lib/coverage-instrumenter.js]: Should account for alternate template file types

File: tests/.eslintrc [hunk 14]
```diff
@@ -0,0 +1,11 @@
+{
```
Comment (rwjblue) [inline tests/.eslintrc]: I'd like this to be `.eslintrc.js`

**Comment by rwjblue** [comment]
OK, I did a round of review, please reply back inline as needed to clarify or confirm my comments.

The changes needed based on my feedback are fairly minor, so perhaps it does make sense to try to fix this up and land it directly instead of separate PR's.

I will try to circle around with @kategengler on it...

**Comment by sandersky** [comment]
@rwjblue I believe I've addressed your concerns. Would love additional feedback when you get a chance.

**Comment by patcoll** [comment]
I am anxious to see a final review + merge for this PR

**Comment by rwjblue** [comment]
Will try to review tonight, thanks for your patience...

**Comment by rwwagner90** [comment]
+1 this looks dope. Glad someone finally got Istanbul up and running!

File: lib/babel-istanbul-instrumenter.js (hunk 8 above)
Comment (rwjblue) [inline lib/babel-istanbul-instrumenter.js]: I'd like to land this PR without this file.  It adds quite a bit of extra weight maintenance wise, and it isn't clear to me how much value it adds.

Can you remove and update?  I'm happy to work through the specific pros/cons in a separate PR after this has landed, but I really don't want to block the other refactors while we hash that out...

**Comment by rwjblue** [comment]
Looks great, only have that one blocker (moving the `lib/babel-istanbul-instrumenter.js` usage into a follow up PR).

**Comment by sglanzer** [comment]
@sandersky ^

**Comment by hbdahl** [comment]
This does definitely look amazing! It would be astronomically beneficial to the community if the updated code gets merged! 👍

File: lib/babel-istanbul-instrumenter.js (hunk 8 above)
Comment (sandersky) [inline lib/babel-istanbul-instrumenter.js]: The value add of this is that the code coverage reports proper line numbers on transpiled code. Without this piece the line numbers are wrong and that makes code coverage metrics a lot less useful.

Comment (rwjblue) [inline lib/babel-istanbul-instrumenter.js]: Sounds like we will have a grand discussion in the follow up PR then. 😸

Comment (sglanzer) [inline lib/babel-istanbul-instrumenter.js]: Absolutely zero offense meant by this, but it seems as though your team may not have enough time available currently to move this project forward with pace.  This is a slight problem for us as I've essentially stopped maintenance of the blanket project in anticipation of this and our company paused all work on ember-cli-istanbul as well.

It may be prudent for us to resume work on ember-cli-istanbul at this stage as we have a minimum of 4 engineers who could contribute to the project immediately.  We would also be happy to grant collaborator status to members of the ember-cli team.

Let me know if this course would be overly controversial but I would rather have a useable, if slightly flawed, product that we iterate on than remain in limbo.

Comment (rwjblue) [inline lib/babel-istanbul-instrumenter.js]: No offense taken, but my requests here seem reasonable (perhaps only to me?) and have been communicated very clearly (for most of the time this PR has been waiting). As I mentioned, a number of times before, once this is addressed, the bulk of the work will be merged and we can have a specific conversation about this file on its own merit.

File: index.js (hunk 7 above)
Comment (rwjblue) [inline index.js]: @sandersky - Has this been addressed?

File: lib/babel-istanbul-instrumenter.js (hunk 8 above)
Comment (sglanzer) [inline lib/babel-istanbul-instrumenter.js]: Fair enough, I'll ask @sandersky to split out the file, having spoken with him yesterday the concern was that:

1. It's a reasonable inclusion given that line numbers don't map correctly otherwise
2. The initial review took around 2 weeks to receive a response

As long as the second PR doesn't get stuck then there really isn't an issue, so we'll split it and go from there.

Thanks for the response - here's to a complete code coverage solution :)

**Comment by sandersky** [comment]
@rwjblue pulled out that chunk of code for a future PR.

**Comment by rwjblue** [comment]
@sandersky - Thank you!!!  Sorry for taking so long on this, but I really appreciate the hard work you have put in here.

Looking forward to that follow up PR...

File: lib/babel-istanbul-instrumenter.js (hunk 8 above)
Comment (sophypal) [inline lib/babel-istanbul-instrumenter.js]: Just to be clear, having this without `babel-istanbul-instrumenter` will add a whole lot of value by itself. Since we're now using the `preprocessTree` hook and `esprima` can inherently parse ES6, we get line numbers that map correct for ES6. The trouble comes only with ES7 features that we have gotten use to using like `decorators`.

Comment (sandersky) [inline lib/babel-istanbul-instrumenter.js]: @sophypal thanks for pointing that out. I can't use this yet because of my use of `ember-computed-decorators` in every app I work on. But I agree the value add for ES6 is definitely there.

**Comment by rwjblue** [comment]
```
% npm publish
+ ember-cli-code-coverage@0.2.0
```

**Comment by sglanzer** [comment]
Awesome :)
